# @package _global_

defaults:
  - override /ds: VOC
  - override /fg@fg_real: VOC/1shot/real # 1 shot real foregrounds
  - override /fg@fg_syn: VOC/fg_template # zero-shot fg template
  - override /bg@bg_real: VOC/1shot/real # 1 shot real backgrounds

name: VOC-demo-1shot-synFg
dataset_dir: ${work_dir}/../data/test_data
paster:
  debug: True
